apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod
  namespace: default
spec:
  containers:
  - name: sec-ctx-vol
    volumeMounts:
    - name: sec-ctx
      mountPath: /pod/demo
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","sleep 60m"]
    securityContext:
      allowPrivilegeEscalation: false
  volumes:
  - name: sec-ctx
    emptyDir: {}
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
