apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-cluster

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods","namespaces"]
  verbs: ["list","get","watch"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets"]
  verbs: ["get","list","create"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: test-clusterrole
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: test-cluster
  namespace: default
