apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-rolebinding
  namespace: kube-system
subjects:
- kind: User
  name: test
  apiGroup: ""
roleRef:
  kind: Role
  name: test-role
  apiGroup: rbac.authorization.k8s.io
