apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-sa-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods","namespaces"]
  verbs: ["list","get","watch"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets"]
  verbs: ["get","list","create"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-sa-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: test-sa-role
  kind: Role
subjects:
- kind: ServiceAccount
  name: test-sa
  namespace: kube-system  
