apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-role
  namespace: kube-system
rules:
- apiGroups: ["","apps"]
  resources: ["deployment","replicasets","pods"]
  verbs: ["list"]