apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels: 
    type: local
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/data/k8s/hostpath"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hotspath
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: pv-hostpath-pod
spec:
  volumes:
  - name: pv-hostpath
    persistentVolumeClaim:
      claimName: pvc-hostpath
  nodeSelector:
    kubernetes.io/hostname: node01
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: ng-port
      containerPort: 80
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: pv-hostpath
