apiVersion: v1
kind: Pod
metadata:
  name: podHook-for-postStart
  namespace: default
spce:
  containers:
  - name: pod-hook-postStart
    image: nginx
    ports:
    - containerPort: 80
    lifecycle:
      postStart:
        exec:
          command:
          - "/bin/bash"
          - "-c"
          - "echo hello from the postStart handler" > /var/log/postStart.log