apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-demo
  namespace: default
  labels:
    type: crontab
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cronb
            image: busybox
            command: ["/bin/sh","-c","for i in 1 2 3 4 5 6 7 8 9;do echo $1;done"]