apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: kube-public
  labels:
    role: ngx-deploy
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

