apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  namespace: default
  labels:
    app: nginx-headless
spec:
  ports:
  - name: http
    port: 80
  clusterIP:  None
  selector:
    app: nginx