apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
  namespace: default
  labels:
    type: job
spec:
  template:
    spec:
      containers:
      - name: counter
        image: busybox
        command: ["/bin/sh","-c","for i in 9 8 7 6 5 4 3 2 1;do echo $i;done"]
      restartPolicy: Never