apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  lables：
    role: nginx-rs
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
      type: nginx-rs
  replicas: 4
  template:
    metadata:
      lables:
        app: nginx
        type: nginx-rs
    spec:
      containers:
      - name: nginx
        image: nginx:1.12.7
        ports:
        - containerPort: 80