apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
  - name: secret1
    image: busybox
    command: ["/bin/sh","-c","echo ${UserName}  ${PassWrod}"]
    env:
    - name: UserName
      valueFrom:
        secretKeyRef:
          name: mysercet
          key: username
    - name: PassWord
      valueFrom:
        secretKeyRef:
          name: mysercet
          key:password