apiVersion: v1
kind: Pod
metadata:
  name: mysecret1
spec:
  containers:
  - name: secret2
    image: busybox
    command: ["/bin/sh","-c","ls /etc/secrets"]
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
  volumes:
  - name: secrets
    secret:
      secretName: mysecret