apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: default
spec:
  volumes:
  - name: workdir
    emptyDir: {}   #生命周期随pod的消亡而消亡
  initContainers:
  - name: download_html
    image: busybox
    command: ["wget","-O","/data/html/index.html","http://www.baidu.com"]
    volumeMounts:
    - name: workdir
      mountPath: /data/html
  containers:
  - name: web
    image: nginx:1.7.9
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html/
