apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
  namespace: default
spec:
  containers:
  - name: resource-pod
    image: nginx:1.7.9
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi
    ports:
    - containerPort: 80    
